# Generated by Django 4.2.7 on 2023-11-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_updated_alter_article_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='descreption',
            new_name='description',
        ),
    ]
